
package sw.wine.livraison.servicestub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-03-07T15:19:07.098+01:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "commandeInconnue", targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/")
public class CommandeInconnueFault extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -4578622398455666643L;
	private java.lang.String commandeInconnue;

    public CommandeInconnueFault() {
        super();
    }
    
    public CommandeInconnueFault(String message) {
        super(message);
    }
    
    public CommandeInconnueFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CommandeInconnueFault(String message, java.lang.String commandeInconnue) {
        super(message);
        this.commandeInconnue = commandeInconnue;
    }

    public CommandeInconnueFault(String message, java.lang.String commandeInconnue, Throwable cause) {
        super(message, cause);
        this.commandeInconnue = commandeInconnue;
    }

    public java.lang.String getFaultInfo() {
        return this.commandeInconnue;
    }
}
