
package sw.wine.livraison.servicestub;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-03-07T15:19:07.573+01:00
 * Generated source version: 2.6.2
 * 
 */
 
public class LivraisonPortType_LivraisonServicePort_Server{

    protected LivraisonPortType_LivraisonServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new LivraisonPortTypeImpl();
        String address = "http://www.example.org/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new LivraisonPortType_LivraisonServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
