
package sw.wine.livraison.servicestub;

import javax.xml.ws.WebFault;

import sw.wine.livraison.Article;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-03-07T15:19:06.906+01:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "nondisponible", targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/")
public class NonDisponibleFault extends Exception {
    
    private java.lang.String nondisponible;
    private static final long serialVersionUID = 1L;
	@SuppressWarnings("unused")
	private String referenceVin;

    public NonDisponibleFault() {
        super();
    }
    
    public NonDisponibleFault(String message) {
        super(message);
    }
    
    public NonDisponibleFault(String message, Throwable cause) {
        super(message, cause);
    }

    public NonDisponibleFault(String message, java.lang.String nondisponible) {
        super(message);
        this.nondisponible = nondisponible;
    }

    public NonDisponibleFault(String message, java.lang.String nondisponible, Throwable cause) {
        super(message, cause);
        this.nondisponible = nondisponible;
    }

    public java.lang.String getFaultInfo() {
        return this.nondisponible;
    }
    public NonDisponibleFault(Article article) {
		super("Le vin " + article.getReferenceVin() + " n'est pas disponible(plus de produit ou prix inconnu)");
		this.referenceVin = article.getReferenceVin();
	}
}
