package sw.wine.livraison.servicestub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-03-07T15:19:07.585+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "LivraisonServiceService", 
                  wsdlLocation = "wptiwe5/base-tp-tiw5/services/WebContent/livraisons.wsdl",
                  targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/") 
public class LivraisonServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/", "LivraisonServiceService");
    public final static QName LivraisonServicePort = new QName("http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/", "LivraisonServicePort");
    static {
        URL url = null;
        try {
            url = new URL("wptiwe5/base-tp-tiw5/services/WebContent/livraisons.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LivraisonServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cmw/Desktop/wptiwe5/base-tp-tiw5/services/WebContent/livraisons.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LivraisonServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LivraisonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LivraisonServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LivraisonServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LivraisonServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LivraisonServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns LivraisonPortType
     */
    @WebEndpoint(name = "LivraisonServicePort")
    public LivraisonPortType getLivraisonServicePort() {
        return super.getPort(LivraisonServicePort, LivraisonPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LivraisonPortType
     */
    @WebEndpoint(name = "LivraisonServicePort")
    public LivraisonPortType getLivraisonServicePort(WebServiceFeature... features) {
        return super.getPort(LivraisonServicePort, LivraisonPortType.class, features);
    }

}
