package sw.wine.livraison.servicestub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-03-07T15:19:07.333+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/", name = "LivraisonPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface LivraisonPortType {

	@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
	@ResponseWrapper(localName = "infos", targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/", className = "sw.wine.livraison.CommandeInfos")
    @RequestWrapper(localName = "commande", targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/", className = "sw.wine.livraison.servicestub.Commande")
    @WebMethod(action = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/commande")
    //@WebResult(name = "infos", targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/", partName = "parameters")
    public void commande(
        @WebParam(name = "vin", targetNamespace = "")
        java.util.List<sw.wine.livraison.servicestub.VinT> vins,
        @WebParam(mode = WebParam.Mode.OUT, name = "id", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> id,
        @WebParam(mode = WebParam.Mode.OUT, name = "prix", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Double> prix
    ) throws NonDisponibleFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "livraisonEffectueeResponse", targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/", partName = "parameters")
    @WebMethod(action = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/livraisonEffectuee")
    public boolean livraisonEffectuee(
        @WebParam(partName = "parameters", name = "livraisonEffectuee", targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/")
        java.lang.String parameters
    ) throws CommandeInconnueFault;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "dateLivraison", targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/", partName = "parameters")
    @WebMethod(action = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/confirmation")
    public javax.xml.datatype.XMLGregorianCalendar confirmation(
        @WebParam(partName = "parameters", name = "confirmation", targetNamespace = "http://www.univ-lyon1.fr/M2TI/TIW5/wine/service/livraisons/")
        java.lang.String parameters
    ) throws NonDisponibleFault, CommandeInconnueFault;
}
